DROP DATABASE IF EXISTS Assignment_9; 
CREATE DATABASE IF NOT EXISTS Assignment_9;
USE Assignment_9;

-- Tạo bảng 
CREATE TABLE `USER`(
	USERID		MEDIUMINT UNIQUE AUTO_INCREMENT,
    `ACCOUNT`	VARCHAR(20) UNIQUE,
	FIRSTNAME	VARCHAR(20),
    LASTNAME	VARCHAR(20),
    EMAIL		VARCHAR(254) UNIQUE,
    PRIMARY KEY (`ACCOUNT`, EMAIL)
);

SELECT * FROM `USER`;
SELECT ACCOUNT FROM `USER` WHERE ACCOUNT = 'moly7x';